language: node_js
env:
  global:
    - GH_REF: github.com/w3c/aria-practices.git
    - secure: "sdG/moGtPSpsjSOKjZwqxZ/4zAHbRvU5a5pKBqfiZIv3lXy6M6HSE6Ywe81R9SO3Ii1Eqx6O5oxCtuabj1mghQ2LnRmTD719PhnqYKkRSxZ7dPX3gJ0F0nY5MbMEjRTIxqPD9UIM6PMAzRqVX/pzwE3y3/VXQqFp7KADYfAE/83dH6QuPC1WMR5bGzxi5hqDe6UU1hs9Veb9k4rOXtTuEuTWrzrrja6t7N6CbhywPfTwF4nPi8NIODLEfv/NyCtn0Uc2TEtC344m8zsSYIXg6iHCBEo7IDVsSgi6PXr2F6pK4/bg8elW05Q1bzPc4AzSRpYlAkU616eoO7akMevGvdrEZo9A04Yt9mW0LzFCz4vrh8LFKJXdc38SrXaUBka6szYv9O2EnFI+p+7PuzXk1Yg/0CFE5AGgr+1YPF8i29EeeNITlTngflW+cjuDF+S70/T62gksv2IMNjW92cO1Nj+gVxbOIs3JNDx7sUcu9Bw6734iXwy06Em1mEXXm/EPsnSqY8VqohEPtzkacQXqvdBgevYOpsuVN28NJZue7+5waMDLsNzdY1E9wCsxdTLDldUA5hSsjPXpuyLrpEn1Y1FSx6jFBhDlscpfdb3/PAw9HTdEsBGq+K2JpbkXKMyTxoUdc3SG+E4WMiYU4YDsOrtncs9dZKVYGmvOSssSl/E="

git:
  depth: 3

branches:
  only:
    master

install:
  - npm install && npm test

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"

script:
  - cd ../..
  - mkdir gh-pages
  - cd gh-pages
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/aria-practices.git
  - cd aria-practices
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/aria-practices/master/aria-practices.html -o index.html -f
  - cp -r ../../w3c/aria-practices/examples .

after_success:
  - git add .
  - git commit -m "Generated by TRAVIS-CI"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages
